[tool.poetry]
name = "scraping_fgo_wiki"
version = "0.1.0"
description = ""
authors = ["085astatine <astatine085@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
lxml = "^4.6.4"
requests = "^2.26.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
